### PR TITLE
Clean up output

### PR DESCRIPTION
**Pull request by edwardloveall**
This makes the output from the converter much cleaner. It deals with whitespace and cleans up the code a bunch. It's still not perfect and runs on an old version of lucky, but this is a good step forward.

### CODE REVIEW

**Review by paulcsmith — APPROVED** [review]
Looks good :)

**Comment by paulcsmith** [comment]
This is awesome. Do you want to deploy it to html2lucky.herokuapp (or some other name like that)? Then we can start linking to it when people have trouble with HTML

**Comment by edwardloveall** [comment]
Yeah, that's my plan. Do you have access to a current heroku deploy? I do not.

**Comment by paulcsmith** [comment]
I don't think there is one, so I think we can create a new one. The original creator had one up but I think we should create a new one that we one. If that one isn't available. Maybe `luckyhtml.herokuapp`. We can put it on a subdomain of `luckyframework.org` later though. What do you think. Does that sound good?

**Comment by edwardloveall** [comment]
Yup! 😄 One silly question, what does `.herokuapp` mean? Just that I should deploy it to heroku? I pretty sure it's not a TLD but that's probably not what you meant.

**Comment by paulcsmith** [comment]
Oh yeah it's the free one you get if you don't set it up with a domain. My bad :P

**Comment by paulcsmith** [comment]
@edwardloveall Is it ok if I squash these commits and force push master so the history is cleaner? It'll prob mess up your repo but if you delete and repull it should be fine. But I wanted to run it by you first to make sure you're cool with it.

Also, did you get a change to put this on Heroku? If not no prob! I'll hop on it. Just don't want to duplicate work if you've already tackled it

**Comment by edwardloveall** [comment]
Hey, sorry for the delay on this. I was going to try to deploy a different app for practice but ran into some other problems with it. I also don't have access to any kind of lucky heroku org and I seem to remember that transferring apps between orgs is a pain. Feel free to squash and/or deploy.

**Comment by paulcsmith** [comment]
@edwardloveall Sounds good! I created an app and will add you as a collaborator. What is the email you would like to me to use?

**Comment by edwardloveall** [comment]
`edward@edwardloveall.com` please!

**Comment by paulcsmith** [comment]
And it's up! https://luckyhtml.herokuapp.com

**Pull request merged**
